name: Upstream Sync

on:
  schedule:
    - cron: '0 3 * * 1' # Monday 03:00 UTC (11:00 Beijing time)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    if: ${{ github.event.repository.fork }}
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork with upstream
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method POST \
            repos/${{ github.repository }}/merge-upstream \
            -f branch=main
